SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID
FROM employees
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM departments
WHERE DEPARTMENT_NAME IN (SELECT DEPARTMENT_NAME FROM departments
    WHERE LOCATION_ID IN (SELECT LOCATION_ID FROM locations
WHERE CITY = 'Seattle'
        )
    ));
